### ISSUE TITLE
Classical engine will beat the model at 100-0

### ISSUE THREAD

**Issue by aletote** [evg-tyurin/alpha-nagibator#2]
I don't get this part. Shouldn't the model beat classical engine? Why do you think it can't?

**Comment by evg-tyurin** [comment]
I mean that the model **committed to the repo** will be beaten by strong classical engine because I performed such experiment before I've written this. The main reason is that the level of the model is quite low. It may win a human which is not so good in checkers for example a child. 

However the model can be improved by continuous training which requires more computational resources. If the model reaches a higher level and beat a classical engine I'll correct the README file and specify the score.
